services:
  backend:
    build: ./backend
    container_name: internship-tracker-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - loki
    volumes:
      - ./backend:/app
      - /app/node_modules
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"

  mongo:
    image: mongo:7
    container_name: internship-tracker-mongo-compose
    ports:
      - "27018:27017"

  grafana:
    image: grafana/grafana:latest
    container_name: internship-tracker-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123

  loki:
    image: grafana/loki:latest
    container_name: internship-tracker-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml